language: node_js
node_js:
  - 12.18.3
cache: yarn

install:
	- yarn ci

script:
	- yarn test
	- yarn run build

deploy:
	- provider: pages
	skip-cleanup: true
	github_token: $GITHUB_TOKEN
	on:
		branch: master

    © 2020 GitHub, Inc.
    Terms
    Privacy
